#server:
#  port: ${PORT:8080}
spring:
  application:
    name: cards
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
#    url: ${SPRING_DATASOURCE_URL}
    url: jdbc:postgresql://34.116.212.216:5432/flashcardsdb
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
   #   ddl-auto: create
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
 #   show-sql: 'true'
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY}

cards:
  images:
    max-size-bytes: 2097152             # 2MB
    allowed-content-types: image/png,image/jpeg

user:
  service:
    url: ${USER_SERVICE_URL}

cors:
  allowed-origin: ${FRONTEND_URL}