server:
  port: 8080

spring:
  application:
    name: user
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
    #  ddl-auto: create
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  #  show-sql: 'true'

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY}
      expiration: 604800000 # 7 days

cards:
  service:
    url: ${CARDS_SERVICE_URL}

cors:
  allowed-origin: ${FRONTEND_URL}