#server:
#  port: ${PORT:8080}

spring:
  application:
    name: user
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
#    url: ${SPRING_DATASOURCE_URL}
    url: jdbc:postgresql://34.116.212.216:5432/flashcardsdb
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
    #  ddl-auto: create
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  #  show-sql: 'true'

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY}
      expiration: ${APPLICATION_SECURITY_JWT_EXPIRATION} # 7 days

cards:
  service:
    url: ${CARDS_SERVICE_URL}

cors:
  allowed-origin: ${FRONTEND_URL}